sonar.projectKey=JulianiusM_CardGameDigital_58cf5480-59d1-4f41-a444-de6ac7fcc9cb
sonar.projectName=CardGameDigital
sonar.sources=apps/server/src,apps/web/src,apps/kodi/resources/lib,packages,tooling
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info,coverage/client/lcov.info
sonar.exclusions=node_modules/**,dist/**,**/*.spec.ts,**/*.png,**/*.jpg,**/*.jpeg,**/*.gif,**/*.sass,apps/server/migrations/**,apps/kodi/resources/data/**
