sonar.projectKey=JulianiusM_CardGameDigital_58cf5480-59d1-4f41-a444-de6ac7fcc9cb
sonar.projectName=CardGameDigital
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info,coverage/client/lcov.info
sonar.exclusions=node_modules/**,dist/**,**/*.spec.ts,src/public/img/**,**/*.png,**/*.jpg,**/*.jpeg,**/*.gif,**/*.sass,src/migrations/**