export const CARD_TYPES = {
    QUESTION: "QUESTION",
    DARE: "DARE",
    CONVERSATION_META: "CONVERSATION_META",
} as const;
export type CardType = (typeof CARD_TYPES)[keyof typeof CARD_TYPES];

export const QUESTION_CATEGORIES = {
    EVERYDAY: "CAT_EVERYDAY",
    CHILDHOOD: "CAT_CHILDHOOD",
    PERSONALITY: "CAT_PERSONALITY",
    SCENARIO: "CAT_SCENARIO",
    INTOXICATION: "CAT_INTOXICATION",
    FRIENDSHIP: "CAT_FRIENDSHIP",
    RELATIONSHIP: "CAT_RELATIONSHIP",
    BODY: "CAT_BODY",
    SEXUALITY: "CAT_SEXUALITY",
    SEX_OPENNESS: "CAT_SEX_OPENNESS",
    SEX_TENSION: "CAT_SEX_TENSION",
    SEX_EXPERIENCE: "CAT_SEX_EXPERIENCE",
} as const;
export type QuestionCategoryId = (typeof QUESTION_CATEGORIES)[keyof typeof QUESTION_CATEGORIES];
/** Canonical presentation order for every Question Category choice group. */
export const QUESTION_CATEGORY_IDS: readonly QuestionCategoryId[] =
    Object.values(QUESTION_CATEGORIES);

export const DARE_TYPES = {
    SILLY: "DARE_SILLY",
    THIRD_PARTY: "DARE_THIRD_PARTY",
    KISS: "DARE_KISS",
    KISS_SPICY: "DARE_KISS_SPICY",
    TOUCH: "DARE_TOUCH",
    TOUCH_SPICY: "DARE_TOUCH_SPICY",
    TOUCH_SEXY: "DARE_TOUCH_SEXY",
    CLOTHING: "DARE_CLOTHING",
    NUDITY: "DARE_NUDITY",
    SEXUAL_TENSION: "DARE_SEXUAL_TENSION",
    BORDERLINE_SEX: "DARE_BORDERLINE_SEX",
    SEX: "DARE_SEX",
    OTHER: "DARE_OTHER",
} as const;
export type DareTypeId = (typeof DARE_TYPES)[keyof typeof DARE_TYPES];
/** Canonical presentation order for every DareType choice group. */
export const DARE_TYPE_IDS: readonly DareTypeId[] = Object.values(DARE_TYPES);

export const OPERATIONAL_FLAGS = {
    REQUIRES_TARGET_PLAYER: "REQUIRES_TARGET_PLAYER",
    INVOLVES_THIRD_PARTY: "INVOLVES_THIRD_PARTY",
    REQUIRES_PHYSICAL_CONTACT: "REQUIRES_PHYSICAL_CONTACT",
    REMOVES_CLOTHING: "REMOVES_CLOTHING",
    REQUIRES_NUDITY: "REQUIRES_NUDITY",
    INVOLVES_ALCOHOL: "INVOLVES_ALCOHOL",
    INVOLVES_RECREATIONAL_SUBSTANCES: "INVOLVES_RECREATIONAL_SUBSTANCES",
} as const;
export type OperationalFlag = (typeof OPERATIONAL_FLAGS)[keyof typeof OPERATIONAL_FLAGS];
