"""Logical routes rendered by the single long-lived WindowXMLDialog shell."""

from __future__ import annotations

from enum import Enum


class Route(str, Enum):
    BOOTSTRAP = "BOOTSTRAP"
    HOME = "HOME"
    SERVER_LIST = "SERVER_LIST"
    SERVER_DETAILS = "SERVER_DETAILS"
    MANUAL_SERVER = "MANUAL_SERVER"
    DEVICE_LINK = "DEVICE_LINK"
    SETUP_GROUP = "SETUP_GROUP"
    SETUP_GROUP_SELECT = "SETUP_GROUP_SELECT"
    SETUP_MODE = "SETUP_MODE"
    SETUP_PROFILE = "SETUP_PROFILE"
    SETUP_PLAYERS = "SETUP_PLAYERS"
    SETUP_PLAYER = "SETUP_PLAYER"
    SETUP_CUSTOMIZE = "SETUP_CUSTOMIZE"
    SETUP_CATEGORIES = "SETUP_CATEGORIES"
    SETUP_DARES = "SETUP_DARES"
    SETUP_FLAGS = "SETUP_FLAGS"
    SETUP_INTENSITY = "SETUP_INTENSITY"
    SETUP_MODE_OPTIONS = "SETUP_MODE_OPTIONS"
    SETUP_OPTIONS = "SETUP_OPTIONS"
    SETUP_CARD_LANGUAGE = "SETUP_CARD_LANGUAGE"
    SETUP_CARD_LANGUAGE_PRIMARY = "SETUP_CARD_LANGUAGE_PRIMARY"
    SETUP_CARD_LANGUAGE_FALLBACKS = "SETUP_CARD_LANGUAGE_FALLBACKS"
    SETUP_CARD_LANGUAGE_FALLBACK_ADD = "SETUP_CARD_LANGUAGE_FALLBACK_ADD"
    SETUP_CARD_LANGUAGE_FALLBACK = "SETUP_CARD_LANGUAGE_FALLBACK"
    SETUP_CARD_POLICY = "SETUP_CARD_POLICY"
    SETUP_POLICY_DEFAULT = "SETUP_POLICY_DEFAULT"
    SETUP_POLICY_RULES = "SETUP_POLICY_RULES"
    SETUP_POLICY_RULE = "SETUP_POLICY_RULE"
    SETUP_POLICY_PREDICATE = "SETUP_POLICY_PREDICATE"
    SETUP_POLICY_VALUES = "SETUP_POLICY_VALUES"
    SETUP_POLICY_DIRECTIVES = "SETUP_POLICY_DIRECTIVES"
    SETUP_EXACT_CARDS = "SETUP_EXACT_CARDS"
    SETUP_EXACT_CARD = "SETUP_EXACT_CARD"
    SETUP_REVIEW = "SETUP_REVIEW"
    ROOM_CREATING = "ROOM_CREATING"
    ROOM_CODE_ENTRY = "ROOM_CODE_ENTRY"
    ROOM_LOBBY_DISPLAY = "ROOM_LOBBY_DISPLAY"
    ROOM_GAME_DISPLAY = "ROOM_GAME_DISPLAY"
    ROOM_DISPLAY_MENU = "ROOM_DISPLAY_MENU"
    ROOM_SUMMARY_DISPLAY = "ROOM_SUMMARY_DISPLAY"
    COUCH_GAME = "COUCH_GAME"
    COUCH_MENU = "COUCH_MENU"
    COUCH_SUMMARY = "COUCH_SUMMARY"
    GROUP_LIST = "GROUP_LIST"
    GROUP_CREATE = "GROUP_CREATE"
    GROUP_MEMBER = "GROUP_MEMBER"
    PREFERENCES = "PREFERENCES"
    HELP = "HELP"
    DIAGNOSTICS = "DIAGNOSTICS"


ACTIVE_ROUTES = frozenset(
    {
        Route.COUCH_GAME,
        Route.ROOM_LOBBY_DISPLAY,
        Route.ROOM_GAME_DISPLAY,
    }
)


SETUP_ROUTES = frozenset(route for route in Route if route.value.startswith("SETUP_"))
